### PR TITLE
Small fixes for dependencies, console spam, and performance

### PR DESCRIPTION
**Pull request by mezz**
Hello,

This PR does the following:
 * Update the gradle script so that it automatically downloads and uses JEI, Waila, and Chickens.
 * Greatly improves performance of `NestPenTileEntity` by skipping chicken collision calculations and AI pathing calculations.
 * Replaces some usages of internal JEI classes which are unsafe to use.
 * Stops console spam of "Skipping Entity with id".

### CODE REVIEW

**Comment by GenDeathrow** [comment]
First off thank you for taking any time to actually make the PR.

Gradle / Maven isn't my strong suit, as I really appreciate you setting that up more efficiently. I had been learning a little bit over time, but I didn't want to mess up the system I was using.

I wish I had pushed the fix, but the skipping entity id. I just figured out last week. While doing that I realized I hadn't been turning off the AI, Even though I pretty sure I told ppl I was. But hadn't thought of the collision detection, that's a great catch. That plus the AI, more than likely solved my increasing tick usage over time.  I have been trying to rewrite a lot of that code cause it got a bit crazy, while I was  learning 1.10.2 forge, plus doing things I hadn't ever messed with (Rendering). 

I'm going to look over a few things before I merge. But I seriously appreciate you doing the PR. Mainly because I know how bad that code is.

**Comment by GenDeathrow** [comment]
Oh and thanks for the JEI help as well. Its the first time I actually used a API Library like that and it was pretty easy to pick up.

**Comment by GenDeathrow** [comment]
lol apparently I forgot I had started to pull jei with maven.. that was also last week, but your looks 100% better than what I did.

**Comment by mezz** [comment]
You're welcome! The gradle stuff is hard to get the hang of. I think it's a lot easier to learn it by example so hopefully this PR helped!

**Comment by GenDeathrow** [comment]
yeah after some testing.. I think ,between having the AI turned off and collision detection it made a huge difference. I ran about 300 pens with little tick lag.  When I know that killed my system before.

**Comment by mezz** [comment]
@GenDeathrow would you mind releasing a 0.2.11 bugfix release with these changes, but without the new Beta features? 
The server I'm on is hesitant to use the Beta until the new features are complete and stable, but also has a crazy number of nesting pens so there is some performance trouble.

**Comment by GenDeathrow** [comment]
The only real beta features were the fertilizer mixer and generator. With the latest version the have seen fairly stable. If your worried could you remove the recipes for those two item?... I may be able to put a fix out still will see.

**Comment by mezz** [comment]
Thanks, that should work.

**Comment by GenDeathrow** [comment]
I hope that works.  I really only keep it beta cause I may change the amt of the RF generation and manure to liquid fertilizer amounts. and I have changed the models for the blocks cause those current ones are place holders. but only mod I fully tested it with was enderIO. but 0 crashes on server test.

**Comment by GenDeathrow** [comment]
there is a bug with the nesting pens Im fixing... its  bad one. trying to have it out tonight @mezz

**Comment by mezz** [comment]
Yeah we are seeing some small issues and rolling back to 0.2.10.

I am passing these on from the server admin:

1. "Render Chicken Flaps" option is no longer working,
2. Compatibility with 'The One Probe Addons" is broken somehow.
3. Nesting Pens now have a right click inventory, seems interesting for the future but they liked the way it was previously.

**Comment by GenDeathrow** [comment]
Was this with 0.3.13 / 0.3.12?

- When I changed the render code, I may have forgotten to add the chicken flaps on/off back in. 
- The One Probe Addon was turned off  for this last version as it wasn't fully finished ,and because of this latest issue. It will be back, and I will finish support for all blocks on the next version. 
- Shift Clicking(with-out a net) will still give all the items just like before, but for ppl with out (hwyla/like it), they will at least know what inside the nesting pens now. It will also show same info as HWYLA in the GUI eventually. I have had ppl bring this to my attention many times, it was always planned to have a gui.

**Comment by GenDeathrow** [comment]
On thing the nesting pens will get is an upgrade slot where you can add insulation, that will reduce the sound produced by the chicken inside of it.

**Pull request merged**
