### PR TITLE
Update de_DE.lang

### PR DESCRIPTION
**Pull request by ACGaming**

### CODE REVIEW

**Comment by ACGaming** [comment]
Stud-muffin translates to _Weiberheld_ or _Geiler Typ_ which means something like womanizer. I was very confused with that translation, so I simply set it to _Inventar_ (inventory). ;D

**Comment by GenDeathrow** [comment]
I noticed the change to inventory. My german is good,  but I know some. Stud-muffin isn't as harsh sounding as womanizer is in english. Its a bit more funny than harsh. The switch to inventory was a good call.

**Comment by ACGaming** [comment]
Alright!
But why did you call the rooster inventory "stud-muffin" in the first place? :D

**Comment by GenDeathrow** [comment]
Actually another person codded it and sent it too me. I completly forgotten about it. But it is a bit funny me, but than again its a word I didnt think about not translating well. I may change it to say inventory so it doesnt translate to womenizer in other languagues. 

Also I was supose to say "my german isn't good, but I know some". My phone syping sucks.

**Comment by ACGaming** [comment]
Interesting story! ;)
For other languages, one is better off with _inventory_ indeed.

And don't forget to merge! ;)

**Pull request merged**
